version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app_network

  api:
    build: ./backend
    ports:
      - "3002:3002"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/credit-card-api
      - PORT=3002

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
    depends_on:
      - frontend
      - api

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - app_network

networks:
  app_network:
